from pathlib import Path
import sys
import time

import lightgbm as lgb
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

from config import Paths, BlockingConfig, TrainConfig, COUNTRY, ENTITY_ID, GT_S1
from io_utils import load_all_sources
from build_pairs import (
    label_candidates,
    report_blocking_recall,
    sample_training_pairs,
    entity_level_split,
)
from features import compute_features, FEATURE_COLUMNS


DATA_ROOT = Path(r".\tests\real_aligned_sample_b")

CAPS = [60, 100, 150]


def evaluate_selected(selected, gt, label):
    labeled = label_candidates(selected, gt)
    report = report_blocking_recall(labeled, gt)

    print(
        f"  {label:30s} | "
        f"pair={report['pair_level_recall']:.4f} | "
        f"entity-full={report['entity_level_full_recall']:.4f}"
    )

    return report


def top_k_by_entity(pairs, scores, k):
    ranked = pairs[["entity_id", "candidate_id"]].copy()
    ranked["rank_score"] = scores

    ranked = ranked.sort_values(
        ["entity_id", "rank_score"],
        ascending=[True, False],
        kind="mergesort",
    )

    return (
        ranked.groupby("entity_id", group_keys=False)
        .head(k)
        .reset_index(drop=True)
    )


def main():
    paths = Paths(root=DATA_ROOT)
    bcfg = BlockingConfig()
    tcfg = TrainConfig()

    print("Loading aligned sample...")
    s1, s2, s3, gt = load_all_sources(paths, split="train")

    all_train_X = []
    all_train_y = []

    validation_parts = []

    # -------------------------------------------------------------
    # Build training/validation feature sets COUNTRY BY COUNTRY,
    # matching the production train_model.py split logic.
    # -------------------------------------------------------------
    for country in sorted(s1[COUNTRY].unique()):
        print()
        print("=" * 90)
        print(f"PREPARING {country}")
        print("=" * 90)

        s1_c = s1[s1[COUNTRY] == country].reset_index(drop=True)
        s2_c = s2[s2[COUNTRY] == country]
        s3_c = s3[s3[COUNTRY] == country]

        gt_c = gt[
            gt[GT_S1].isin(s1_c[ENTITY_ID])
        ].copy()

        train_ids, val_ids = entity_level_split(
            s1_c[ENTITY_ID],
            tcfg.val_fraction,
            tcfg.random_seed,
        )

        print(
            f"S1={len(s1_c):,} | "
            f"train entities={len(train_ids):,} | "
            f"validation entities={len(val_ids):,}"
        )

        # Reuse candidate files generated by diag_rank_analysis.py.
        ranked_path = Path(f".ranked_{country}.parquet")

        if not ranked_path.exists():
            raise FileNotFoundError(
                f"{ranked_path} not found. "
                "Run diag_rank_analysis.py first."
            )

        candidates = pd.read_parquet(ranked_path)

        print(f"Raw candidates loaded: {len(candidates):,}")

        train_candidates = candidates[
            candidates[ENTITY_ID].isin(train_ids)
        ].copy()

        val_candidates = candidates[
            candidates[ENTITY_ID].isin(val_ids)
        ].copy()

        # ---------------------------------------------------------
        # Train-side sampling: same hard-negative strategy as
        # the production pipeline.
        # ---------------------------------------------------------
        sampled_train = sample_training_pairs(
            train_candidates,
            negatives_per_positive=tcfg.negatives_per_positive,
            random_seed=tcfg.random_seed,
        )

        print(
            f"Training candidate pairs after sampling: "
            f"{len(sampled_train):,} "
            f"(positives={int(sampled_train['label'].sum()):,})"
        )

        # ---------------------------------------------------------
        # Normalize source data for feature computation.
        # ---------------------------------------------------------
        s1n = __import__("blocking").build_normalized_frame(
            s1_c,
            bcfg.ngram_n,
        )
        s2n = __import__("blocking").build_normalized_frame(
            s2_c,
            bcfg.ngram_n,
        )
        s3n = __import__("blocking").build_normalized_frame(
            s3_c,
            bcfg.ngram_n,
        )

        other_norm = pd.concat(
            [s2n, s3n],
            ignore_index=True,
        )

        print("Computing training features...")
        t0 = time.time()

        train_features = compute_features(
            sampled_train,
            s1n,
            other_norm,
        )

        print(
            f"Training features computed in "
            f"{time.time() - t0:.1f}s"
        )

        all_train_X.append(
            train_features[FEATURE_COLUMNS]
        )
        all_train_y.append(
            sampled_train["label"].astype(np.uint8).to_numpy()
        )

        # Keep all validation raw candidates for ranking.
        validation_parts.append(
            (
                country,
                val_candidates,
                gt_c,
                s1n,
                other_norm,
            )
        )

    # -------------------------------------------------------------
    # Train one global pre-ranker, matching the architecture of the
    # existing production model.
    # -------------------------------------------------------------
    X_train = pd.concat(
        all_train_X,
        ignore_index=True,
    )

    y_train = np.concatenate(all_train_y)

    print()
    print("=" * 90)
    print("TRAINING PRE-CAP RANKER")
    print("=" * 90)

    print(f"Training rows: {len(X_train):,}")
    print(f"Positive rows: {int(y_train.sum()):,}")
    print(f"Negative rows: {int((y_train == 0).sum()):,}")

    params = dict(tcfg.lgbm_params)

    # This is an isolated diagnostic. Keep training substantially smaller
    # than the production 2000-tree setting.
    params["n_estimators"] = 500

    model = lgb.LGBMClassifier(**params)

    t0 = time.time()

    model.fit(
        X_train,
        y_train,
    )

    print(
        f"Pre-ranker trained in "
        f"{time.time() - t0:.1f}s"
    )

    # -------------------------------------------------------------
    # Held-out evaluation.
    # -------------------------------------------------------------
    print()
    print("=" * 90)
    print("HELD-OUT PRE-CAP RANKING RESULTS")
    print("=" * 90)

    for country, val_candidates, gt_c, s1n, other_norm in validation_parts:

        print()
        print(f"COUNTRY: {country}")

        # IMPORTANT: evaluation must use ONLY the held-out S1 entities.
        # val_candidates contains only validation entities, so the GT
        # denominator must be restricted to those same entities.
        eval_gt = gt_c[
            gt_c[GT_S1].isin(
                val_candidates[ENTITY_ID]
            )
        ].copy()

        print(
            f"Validation GT rows: {len(eval_gt):,} | "
            f"Validation candidate entities: "
            f"{val_candidates[ENTITY_ID].nunique():,}"
        )

        # Existing baseline.
        for cap in CAPS:
            current = (
                val_candidates
                .sort_values(
                    ["entity_id", "n_keys"],
                    ascending=[True, False],
                    kind="mergesort",
                )
                .groupby("entity_id", group_keys=False)
                .head(cap)
            )

            evaluate_selected(
                current,
                eval_gt,
                f"current n_keys cap={cap}",
            )

        # Feature computation for ALL validation candidates.
        print(
            f"Computing validation features for "
            f"{len(val_candidates):,} raw candidates..."
        )

        t0 = time.time()

        val_features = compute_features(
            val_candidates,
            s1n,
            other_norm,
        )

        print(
            f"Validation features computed in "
            f"{time.time() - t0:.1f}s"
        )

        scores = model.predict_proba(
            val_features[FEATURE_COLUMNS]
        )[:, 1]

        # Learned ranking.
        for cap in CAPS:
            selected = top_k_by_entity(
                val_candidates,
                scores,
                cap,
            )

            evaluate_selected(
                selected,
                eval_gt,
                f"learned pre-ranker cap={cap}",
            )

        # Compare theoretical uncapped blocker ceiling.
        evaluate_selected(
            val_candidates,
            eval_gt,
            "raw blocking ceiling",
        )

    print()
    print("=" * 90)
    print("DONE")
    print("=" * 90)


if __name__ == "__main__":
    main()


